services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=DATABASE_PASSWORD
    ports:
      - 27017:27017

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=DATABASE_NAME
      - MONGO_USER=DATABASE_USERNAME
      - MONGO_PASS=DATABASE_PASSWORD
    depends_on:
      - mongodb